server:
  port: 2002
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafka-java-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      name: transaction.notification