version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - core-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
      image: confluentinc/cp-kafka:latest
      networks:
        - core-network
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
      image: obsidiandynamics/kafdrop:latest
      networks:
        - core-network
      depends_on:
        - kafka
      ports:
        - "19000:9000"
      environment:
        KAFKA_BROKERCONNECT: kafka:29092
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - core-network
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - core-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
     - "27017:27017"
    volumes:
    - mongodb_data:/data/db
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - core-network
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
  vault:
    image: vault:latest
    container_name: vault
    networks:
      - core-network
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vOU1OCs0IDS6pjr6xGKgkq9AVWhCrs4fo5dVvuK3UDk"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - "vault-logs:/vault/logs"
      - "vault-file:/vault/file"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
#    container_name: elasticsearch_springboot
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.type=single-node"
#      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#    volumes:
#      - elasticsearch_data:/usr/share/elasticsearch/data
#    networks:
#      - core-network
#
#  kibana:
#      image: docker.elastic.co/kibana/kibana:8.3.3
#      container_name: kibana_springboot
#      ports:
#        - "5601:5601"
#      environment:
#        ELASTICSEARCH_URL: http://elasticsearch:9200
#        ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
#      depends_on:
#        - elasticsearch
#      networks:
#        - core-network
#
#  logstash:
#      image: docker.elastic.co/logstash/logstash:8.3.3
#      container_name: logstash_springboot
#      volumes:
#        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
#      ports:
#        - "5044:5044"
#        - "5000:5000/tcp"
#        - "5000:5000/udp"
#        - "9600:9600"
#      environment:
#        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#      networks:
#        - core-network
#      depends_on:
#        - elasticsearch
networks:
  core-network:
    driver: bridge
volumes:
  mysqldb_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  vault-logs:
    driver: local
  vault-file:
    driver: local
#  elasticsearch_data:
#    driver: local
