version: "3"
services:
  user-service:
    container_name: user-service
    build: ../../user-service
    ports:
      - "8081:8081"
    networks:
      - core-network
  account-service:
    container_name: account-service
    build: ../../account-service
    ports:
      - "8086:8086"
    networks:
      - core-network