version: "3"
services:
  user-service:
    container_name: user-service
    build: ../../user-service
    volumes:
      - ~/nagarro/user-service:/logs
    ports:
      - "8081:8081"
    networks:
      - pre-defined-images_core-network
  account-service:
    container_name: account-service
    build: ../../account-service
    volumes:
      - ~/nagarro/account-service:/logs
    ports:
      - "8086:8086"
    networks:
      - pre-defined-images_core-network
  identity-service:
    container_name: identity-service
    build: ../../identity-service
    volumes:
      - ~/nagarro/identity-service:/logs
    ports:
      - "8082:8082"
    networks:
      - pre-defined-images_core-network
  transaction-service:
    container_name: transaction-service
    build: ../../transaction-service
    volumes:
      - ~/nagarro/transaction-service:/logs
    ports:
      - "8087:8087"
    networks:
      - pre-defined-images_core-network
  notification-service:
    container_name: notification-service
    build: ../../notification-service
    volumes:
      - ~/nagarro/notification-service:/logs
    ports:
      - "8088:8088"
    networks:
      - pre-defined-images_core-network
networks:
  pre-defined-images_core-network:
    external: true