spring:
  application:
    name: account-service
    version: 1.0
  profiles:
    active:
      - development
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/account-db?autoReconnect=true&useSSL=false
    url: jdbc:mysql://mysql:3306/account_db?autoReconnect=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: configserver:http://config-server:8888

server:
  port: 8086
