pipeline{

	agent any
	tools {
		maven
	}	

	environment {
		DOCKERHUB_CREDENTIALS=credentials('Nagarro_POC_DockerHub')
	}

	stages {

		stage('Build') {

			steps {
				dir('account-service') {
				sh 'docker build -t nagarropoc/account-service:latest .'	
				//cd account-service
				}
				//sh 'docker build -t nagarropoc/account-service:latest .'
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push nagarropoc/account-service:latest'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}
